---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  availability_zone: <%= require 'spothop'; SpotHop.GetPricing(ENV['EC2_INSTANCE_TYPE'],ENV['AWS_REGION'])[:availability_zone] %>
  price: <%= require 'spothop'; SpotHop.GetPricing(ENV['EC2_INSTANCE_TYPE'],ENV['AWS_REGION'])[:spot_price].to_f %>
  retryable_tries: 100
  retryable_sleep: 10
  instance_type: <%= ENV['EC2_INSTANCE_TYPE'] || 'm3.medium' %>
  security_group_ids: ["kitchen_tests"]

transport:
  username: ubuntu

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-14.04-ec2
    driver:
      image_id: <%=ENV['AWS_UBUNTU_1404_AMI'] %>

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[unifi]
    attributes:
