---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        memory: 768

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[unifi]
    attributes:
