---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.9
  - name: debian-8.2

suites:
- name: default
  run_list:
    - recipe[apt]
    - recipe[unifi]
  attributes:
    apt:
      compile_time_update: true
